# -*- coding: utf-8 -*-
"""Autonomous AutoGen Team.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10kotrSQHpqJLcyvGj0hp_eS-p9J3LWwv
"""

!pip install -q autogen-agentchat autogen-ext[openai]

import autogen_agentchat
import autogen_ext

print("AutoGen installed successfully!")

from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import TextMentionTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient

print("AutoGen components loaded!")

import os

GEMINI_API_KEY = "AQ.Ab8RN6Jc0pUcWsGa4B9vyD6FUEFFfH-YZgNeY5Zd3-sf693yvA"

model_client = OpenAIChatCompletionClient(
    model="gemini-3.6-flash",
    api_key=GEMINI_API_KEY,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "family": "unknown",
    }
)

print("Gemini AutoGen model client created!")

from autogen_agentchat.agents import AssistantAgent

coder = AssistantAgent(
    name="Coder",
    model_client=model_client,
    system_message="""
You are a Python Coder Agent.

Your job is to:
1. Understand the user's programming problem.
2. Write a correct Python solution.
3. Explain the code briefly.
4. If the Reviewer identifies an error, fix the code.
"""
)

reviewer = AssistantAgent(
    name="Reviewer",
    model_client=model_client,
    system_message="""
You are a strict Code Reviewer Agent.

Your job is to:
1. Review the Coder's solution.
2. Find bugs, logical errors, or missing requirements.
3. Suggest specific corrections.
4. If the code is correct, respond with APPROVED.
"""
)

print("Coder Agent created!")
print("Reviewer Agent created!")

from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import TextMentionTermination

termination = TextMentionTermination("APPROVED")

team = RoundRobinGroupChat(
    participants=[coder, reviewer],
    termination_condition=termination,
    max_turns=6
)

print("Autonomous Coder-Reviewer Team created! 🤖🔍")

team = RoundRobinGroupChat(
    participants=[coder, reviewer],
    max_turns=2
)

print("Lightweight team created!")

task = """
Write a Python function called square(n) that returns n * n.
Keep the solution simple and include one test case.
"""

result = await team.run(task=task)

print(result)

conversation_state = {
    "task": "Write a Python function to calculate the factorial of a number.",
    "coder_status": "waiting",
    "reviewer_status": "waiting",
    "code": None,
    "feedback": None,
    "approved": False
}

print("Initial State:")
print(conversation_state)

conversation_state["coder_status"] = "completed"
conversation_state["code"] = """
def factorial(n):
    if n < 0:
        return None

    result = 1

    for i in range(1, n + 1):
        result *= i

    return result
"""

conversation_state["reviewer_status"] = "reviewed"
conversation_state["feedback"] = "Code looks correct."
conversation_state["approved"] = True

print("Updated State:")
print(conversation_state)



