# -*- coding: utf-8 -*-
"""local fine tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQFeVcN9t1CRQ1ue8JxmLxYXRWANFfax
"""

training_data = [
    {
        "instruction": "Explain what machine learning is.",
        "input": "",
        "output": "Machine learning is a branch of artificial intelligence where computers learn patterns from data to make predictions or decisions."
    },
    {
        "instruction": "Explain what a vector database is.",
        "input": "",
        "output": "A vector database stores numerical representations called embeddings and allows efficient similarity searches."
    },
    {
        "instruction": "Explain Retrieval Augmented Generation.",
        "input": "",
        "output": "RAG retrieves relevant information from external documents and provides that information to a language model as context before generating an answer."
    }
]

print("Number of training examples:", len(training_data))

import json

with open("fine_tuning_dataset.jsonl", "w", encoding="utf-8") as f:
    for example in training_data:
        f.write(json.dumps(example, ensure_ascii=False) + "\n")

print("JSONL dataset created successfully!")

with open("fine_tuning_dataset.jsonl", "r", encoding="utf-8") as f:
    print(f.read())

required_fields = ["instruction", "input", "output"]

for i, example in enumerate(training_data):
    missing = [field for field in required_fields if field not in example]

    if missing:
        print(f"❌ Example {i+1} missing: {missing}")
    else:
        print(f"✅ Example {i+1} is valid")

import re

secret_patterns = [
    r"api[_-]?key",
    r"password",
    r"secret",
    r"token",
    r"private[_-]?key"
]

def security_scan(text):
    text = text.lower()

    for pattern in secret_patterns:
        if re.search(pattern, text):
            return False

    return True


for i, example in enumerate(training_data):
    combined_text = " ".join(str(value) for value in example.values())

    if security_scan(combined_text):
        print(f"🛡️ Example {i+1}: SAFE")
    else:
        print(f"⚠️ Example {i+1}: POSSIBLE SECRET")

def validate_quality(data):
    valid = []

    for i, example in enumerate(data):
        instruction = example["instruction"].strip()
        output = example["output"].strip()

        if not instruction:
            print(f"❌ Example {i+1}: empty instruction")
            continue

        if not output:
            print(f"❌ Example {i+1}: empty output")
            continue

        valid.append(example)

    return valid


clean_data = validate_quality(training_data)

print("Original examples:", len(training_data))
print("Valid examples:", len(clean_data))

instructions = [item["instruction"].strip().lower() for item in clean_data]

if len(instructions) == len(set(instructions)):
    print("✅ No duplicate instructions found")
else:
    print("⚠️ Duplicate instructions found")

with open("fine_tuning_dataset_clean.jsonl", "w", encoding="utf-8") as f:
    for example in clean_data:
        f.write(json.dumps(example, ensure_ascii=False) + "\n")

print("✅ Clean JSONL dataset created!")

import json

with open("fine_tuning_dataset_clean.jsonl", "r", encoding="utf-8") as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    try:
        example = json.loads(line)

        if all(field in example for field in ["instruction", "input", "output"]):
            print(f"✅ Line {i+1}: Valid JSONL")
        else:
            print(f"❌ Line {i+1}: Missing required field")

    except json.JSONDecodeError:
        print(f"❌ Line {i+1}: Invalid JSON")

print("\nTotal training examples:", len(lines))

